# permissions for end users to edit iptables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iptables-editor-role
rules:
- apiGroups:
  - kubeedge.kubesphere.io
  resources:
  - iptables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeedge.kubesphere.io
  resources:
  - iptables/status
  verbs:
  - get
